### ISSUE TITLE
How is this tool actually used?

### ISSUE THREAD

**Issue by steoj** [Josverl/vfs_merge#5]
Question from a noob here:

This looks exactly what I need to make sure my firmware is bundled with my `boot.py` and my `main.py` when flashing my ESP32.
Its a python program, I get that, but what command line actions are actually needed to make this happen?

I can open the repo in VSCode and it starts up a container environment for me. Something goes wrong and I@m not sure how to actually make the merge with src and firmware.
![Screenshot 2024-05-07 at 06 44 40](https://github.com/Josverl/vfs_merge/assets/46670655/3201d72e-9fda-4e02-826b-af868f10339e)

Running Mac M3

**Comment by steoj** [comment]
Got a little further by understanding and discovering `poetry`!
Managed to create a distribution file `dist/vfs_merge-0.1.0-py3-none-any.whl` and may install this locally by running:
```bash
pipx install dist/vfs_merge-0.1.0-py3-none-any.whl
```

All well and good. Moving to my project I run:
```bash
vfsmerge --port esp32 --firmware ./boards/CUSTOM_ESP32/build/micropython.bin
```
but this causes the whole thing to exit by:
```log
sten.johnsen$ vfsmerge --port esp32 --firmware ./boards/CUSTOM_ESP32/build/micropython.bin
Traceback (most recent call last):
  File "/Users/sten.johnsen/.local/bin/vfsmerge", line 5, in <module>
    from vfs_merge.__main__ import cli
  File "/Users/sten.johnsen/.local/pipx/venvs/vfs-merge/lib/python3.12/site-packages/vfs_merge/__main__.py", line 11, in <module>
    from .create_littlefs import folder_to_lfs
  File "/Users/sten.johnsen/.local/pipx/venvs/vfs-merge/lib/python3.12/site-packages/vfs_merge/create_littlefs.py", line 9, in <module>
    from littlefs import LittleFS
  File "/Users/sten.johnsen/.local/pipx/venvs/vfs-merge/lib/python3.12/site-packages/littlefs/__init__.py", line 5, in <module>
    from pkg_resources import DistributionNotFound, get_distribution
ModuleNotFoundError: No module named 'pkg_resources'
```

I am missing something, but what?

**Comment by Josverl** [comment]
I never tried pipx from a wheel , but it appears it is missing one of the dependencies 
did you do a poetry build before ?

background: 
I pulled this tool out of another project - but never published it to PyPI. until just now - but it still needs some fit an finish to setup the folder and file structure correctly.
you could try if the package from PyPI works better - and without needing to build from a clone 

If you need/want to build from a clone for now the quick-steps are :

bootstrap toolchain ( one time) 
- `pipx install poetry `

clone and install
- `git clone` to a local_folder 
- `cd local_folder`
- `poetry install `# this will setup a .venv 

to run 
- activate the .venv ( many ways to do it - poetry shell is one) 
- `vfsmerge --port esp32 --firmware ./boards/CUSTOM_ESP32/build/micropython.bin`

**Comment by steoj** [comment]
Thanks for your quick and helpful reply.
Helped a lot that you published it! 
Using vfs_merge as part of my build pipeline and it seems `vfs_merge` expects `esptool` to be callable not `esptool.py`
This task:
```yaml
    - name: Merge with src files
      run: |
        pip install vfs_merge
        mkdir build
        vfsmerge --port esp32 --firmware ./boards/CUSTOM_ESP32/build/micropython.bin
```
causes
![Screenshot 2024-05-08 at 06 47 10](https://github.com/Josverl/vfs_merge/assets/46670655/4abc00d4-70d6-4337-ba59-1b19803c932c)

Note that I also have to create the `build` folder as  writing the `littlefs.img` otherwise fails.

I can reproduce this locally and running 
```bash
esptool.py --chip esp32 merge_bin -o build/firmware_lfs.bin --flash_mode dio --flash_size 4MB 0x1000 boards/CUSTOM_ESP32/build/micropython.bin 0x00200000 build/littlefs.img
```
produces a binary in build/firmware_lfs.bin

**Comment by Josverl** [comment]
I can update the code to create a ./build folder if it does not exists.

I think i've  seen the behaviour on subprocess.run with some other tools as well.
it is caused by the now process not inherting the python environment and I think I know how to fix that by using
`subprocess.run(f"{sys.executable} -m esptool ....`) rather than hoping that the OS already knows where to fid the python script for the environment

**Comment by Josverl** [comment]
✅ Publishing vfs-merge (0.1.2) to PyPI

Once you have it working I'd love a copy/example of your workflow to add to the documentation

**Comment by steoj** [comment]
Thanks for following up. Although I can create a micropython.bin, load it to the ESP32 dev board and run, loading the binary created by vfd_merge will not fly. Checking the binaries with mp-image-tool-esp32 reveals something a little worrying to me:
![Screenshot 2024-05-10 at 13 42 13](https://github.com/Josverl/vfs_merge/assets/46670655/f7053b85-8616-4e2f-8bc8-02a36d240b13)
Invalid firmware header might be linked to the fact that my esp32 refuses to boot after loading. Flashing 
```bash
esptool.py --chip esp32 -p $(PORT) -b $(BAUD) --before default_reset --after hard_reset write_flash --flash_mode=dio
--flash_size=4MB	--flash_freq 40m 0x1000  build/bootloader/bootloader.bin 0x8000  build/partition_table/partition-table.bin 0x10000 build/micropython.bin
```
makes REPL start and everyone is happy (less the python files in the SRC directory that is).
I'm also noticing from the debug info that vfs_merge is running esptool v4.5, while I locally (installed with homebrew) have v4.7. Might that have anything to do with my unfortunate result?
